# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2026 FinKey
"""
Lexicon for ``llm_primary`` trivial skip — messages that never need web search.

~300 RU/EN greetings, acknowledgements, filler, and meta-chat tokens.
Cerebras semantic classifier still runs for every substantive user turn.
"""
from __future__ import annotations

# Exact multi-word phrases (matched after normalization).
TRIVIAL_NO_PHRASES: frozenset[str] = frozenset(
    {
        # ── RU greetings & closings ──
        "привет",
        "приветик",
        "приветствую",
        "здравствуй",
        "здравствуйте",
        "добрый день",
        "доброе утро",
        "добрый вечер",
        "доброй ночи",
        "доброго дня",
        "доброго утра",
        "доброго вечера",
        "доброй ночи",
        "салют",
        "хай",
        "хелло",
        "хеллоу",
        "здорово",
        "здорова",
        "здарова",
        "здаров",
        "ку",
        "ку-ку",
        "куку",
        "йо",
        "йоу",
        "привет всем",
        "всем привет",
        "приветствую вас",
        "рад тебя видеть",
        "рада тебя видеть",
        "рад вас видеть",
        "рада вас видеть",
        "пока",
        "до свидания",
        "до встречи",
        "до завтра",
        "до скорого",
        "увидимся",
        "прощай",
        "бай",
        "бай бай",
        "бай-бай",
        "пока-пока",
        "на связи",
        "удачи",
        "всего хорошего",
        "всего доброго",
        "хорошего дня",
        "хорошего вечера",
        "спокойной ночи",
        "сладких снов",
        # ── RU thanks & politeness ──
        "спасибо",
        "спасибочки",
        "спасибо большое",
        "большое спасибо",
        "огромное спасибо",
        "спасибо тебе",
        "спасибо вам",
        "благодарю",
        "благодарствую",
        "благодарю вас",
        "благодарю тебя",
        "очень признателен",
        "очень признательна",
        "пожалуйста",
        "не за что",
        "не стоит благодарности",
        "извини",
        "извините",
        "прости",
        "простите",
        "извини меня",
        "извините меня",
        "прости меня",
        "простите меня",
        "мне жаль",
        "сорри",
        "сори",
        "пардон",
        "прошу прощения",
        "извиняюсь",
        # ── RU acknowledgements & filler ──
        "да",
        "нет",
        "ага",
        "угу",
        "неа",
        "ну да",
        "ну нет",
        "конечно",
        "разумеется",
        "естественно",
        "безусловно",
        "точно",
        "точно так",
        "именно",
        "верно",
        "правильно",
        "неправильно",
        "ок",
        "окей",
        "окей окей",
        "ладно",
        "хорошо",
        "отлично",
        "прекрасно",
        "замечательно",
        "супер",
        "класс",
        "классно",
        "круто",
        "клёво",
        "клево",
        "крутяк",
        "шикарно",
        "великолепно",
        "идеально",
        "понял",
        "поняла",
        "понятно",
        "ясно",
        "понял тебя",
        "понял вас",
        "принял",
        "принято",
        "согласен",
        "согласна",
        "не согласен",
        "не согласна",
        "может быть",
        "наверное",
        "наверно",
        "возможно",
        "не знаю",
        "хз",
        "ну",
        "ну ладно",
        "ну ок",
        "ну хорошо",
        "ладно ок",
        "всё ок",
        "все ок",
        "всё норм",
        "все норм",
        "норм",
        "нормально",
        "ничего",
        "ничего страшного",
        "не проблема",
        "без проблем",
        "окей понял",
        "ок понял",
        "хм",
        "хмм",
        "эм",
        "ээ",
        "мм",
        "ммм",
        "ого",
        "вау",
        "ого как",
        "лол",
        "кек",
        "хаха",
        "хахаха",
        "ахах",
        "ахаха",
        "ахахах",
        "ржу",
        "смешно",
        "интересно",
        "понятно спасибо",
        "спасибо понял",
        "спасибо понятно",
        "да спасибо",
        "нет спасибо",
        "да пожалуйста",
        "ок спасибо",
        # ── RU small talk ──
        "как дела",
        "как ты",
        "как сам",
        "как сама",
        "как жизнь",
        "как настроение",
        "что нового",
        "как поживаешь",
        "как поживаете",
        "как оно",
        "как там",
        "ты как",
        "вы как",
        "что как",
        "ну как",
        "как успехи",
        "как прошло",
        "как прошёл день",
        "как прошел день",
        "как день",
        "как вечер",
        "как утро",
        "ты тут",
        "ты здесь",
        "ты на месте",
        "на связи",
        "я тут",
        "я здесь",
        "я на месте",
        "слушаю",
        "слушаю тебя",
        "слушаю вас",
        "говори",
        "продолжай",
        "продолжайте",
        "давай",
        "давайте",
        "поехали",
        "погнали",
        "начнём",
        "начнем",
        "стоп",
        "стой",
        "подожди",
        "подождите",
        "минутку",
        "секунду",
        "секундочку",
        "погоди",
        "погодите",
        "ещё раз",
        "еще раз",
        "повтори",
        "повторите",
        "не понял",
        "не поняла",
        "не понял тебя",
        "не понял вас",
        "что",
        "что?",
        "а?",
        "да?",
        "нет?",
        "правда?",
        "серьёзно",
        "серьезно",
        "шутишь",
        "ты шутишь",
        "не может быть",
        "класс спасибо",
        "отлично спасибо",
        "хорошо спасибо",
        "молодец",
        "умница",
        "браво",
        "так держать",
        "приятно",
        "приятно познакомиться",
        "рад знакомству",
        "рада знакомству",
        # ── RU meta / about chat ──
        "ты тут",
        "ты здесь",
        "работаешь",
        "ты работаешь",
        "ты живой",
        "ты живая",
        "ты бот",
        "ты ии",
        "ты ai",
        "кто ты",
        "что ты",
        "ты кто",
        "помоги",
        "помогите",
        "помоги мне",
        "помогите мне",
        "нужна помощь",
        "мне нужна помощь",
        # ── EN greetings & closings ──
        "hello",
        "hi",
        "hey",
        "heya",
        "hiya",
        "howdy",
        "yo",
        "sup",
        "wassup",
        "whats up",
        "what's up",
        "what is up",
        "good morning",
        "good afternoon",
        "good evening",
        "good night",
        "good day",
        "morning",
        "evening",
        "gm",
        "gn",
        "hi there",
        "hey there",
        "hello there",
        "hi everyone",
        "hey everyone",
        "hello everyone",
        "nice to meet you",
        "pleased to meet you",
        "good to see you",
        "great to see you",
        "bye",
        "goodbye",
        "good bye",
        "see you",
        "see ya",
        "see you later",
        "see ya later",
        "later",
        "cya",
        "take care",
        "farewell",
        "good luck",
        "have a good day",
        "have a nice day",
        "have a great day",
        "have a good evening",
        "have a good night",
        "sweet dreams",
        "sleep well",
        "talk soon",
        "talk to you later",
        "ttyl",
        "brb",
        "be right back",
        "gtg",
        "gotta go",
        "im off",
        "i'm off",
        "signing off",
        # ── EN thanks & politeness ──
        "thanks",
        "thank you",
        "thank u",
        "thx",
        "ty",
        "tysm",
        "tyvm",
        "thanks a lot",
        "thanks so much",
        "thanks very much",
        "many thanks",
        "much appreciated",
        "appreciate it",
        "i appreciate it",
        "thanks mate",
        "thanks buddy",
        "cheers",
        "please",
        "pls",
        "plz",
        "you're welcome",
        "youre welcome",
        "no problem",
        "no worries",
        "not a problem",
        "dont mention it",
        "don't mention it",
        "my pleasure",
        "anytime",
        "sorry",
        "so sorry",
        "im sorry",
        "i'm sorry",
        "my bad",
        "my mistake",
        "pardon",
        "pardon me",
        "excuse me",
        "forgive me",
        "apologies",
        "i apologize",
        "i apologise",
        # ── EN acknowledgements & filler ──
        "yes",
        "no",
        "yep",
        "yeah",
        "yea",
        "yup",
        "nope",
        "nah",
        "nay",
        "sure",
        "ok",
        "okay",
        "okey",
        "k",
        "kk",
        "alright",
        "all right",
        "fine",
        "cool",
        "nice",
        "great",
        "awesome",
        "wonderful",
        "perfect",
        "excellent",
        "fantastic",
        "amazing",
        "brilliant",
        "lovely",
        "sweet",
        "dope",
        "sick",
        "lit",
        "got it",
        "gotcha",
        "understood",
        "i understand",
        "i see",
        "i get it",
        "makes sense",
        "that makes sense",
        "sounds good",
        "sounds great",
        "sounds fine",
        "works for me",
        "fair enough",
        "true",
        "right",
        "correct",
        "exactly",
        "precisely",
        "indeed",
        "absolutely",
        "definitely",
        "certainly",
        "of course",
        "for sure",
        "no doubt",
        "maybe",
        "perhaps",
        "possibly",
        "probably",
        "i guess",
        "i think so",
        "not sure",
        "idk",
        "i dont know",
        "i don't know",
        "dunno",
        "well",
        "hmm",
        "hm",
        "uh",
        "uhh",
        "um",
        "umm",
        "er",
        "erm",
        "wow",
        "whoa",
        "omg",
        "oh",
        "ohh",
        "ah",
        "aha",
        "ugh",
        "lol",
        "lmao",
        "rofl",
        "haha",
        "hahaha",
        "hehe",
        "hehehe",
        "funny",
        "interesting",
        "thanks got it",
        "ok thanks",
        "okay thanks",
        "thanks ok",
        "yes please",
        "no thanks",
        "yes thanks",
        "no thank you",
        # ── EN small talk ──
        "how are you",
        "how r u",
        "how are u",
        "how you doing",
        "how are you doing",
        "hows it going",
        "how's it going",
        "how goes it",
        "how have you been",
        "whats new",
        "what's new",
        "hows life",
        "how's life",
        "hows your day",
        "how's your day",
        "how was your day",
        "you there",
        "you here",
        "are you there",
        "are you here",
        "still there",
        "anyone there",
        "hello anyone there",
        "im here",
        "i'm here",
        "im listening",
        "i'm listening",
        "go on",
        "go ahead",
        "continue",
        "lets go",
        "let's go",
        "lets start",
        "let's start",
        "start",
        "begin",
        "stop",
        "wait",
        "hold on",
        "one sec",
        "one second",
        "just a sec",
        "just a moment",
        "hang on",
        "again",
        "once more",
        "repeat",
        "say again",
        "come again",
        "didnt get that",
        "didn't get that",
        "what",
        "huh",
        "really",
        "seriously",
        "no way",
        "you kidding",
        "are you kidding",
        "just kidding",
        "jk",
        "good job",
        "well done",
        "nice work",
        "great job",
        "keep it up",
        "help",
        "help me",
        "i need help",
        "can you help",
        "need assistance",
    }
)

# Single tokens valid in short multi-word trivial messages (≤5 words, all from this set).
TRIVIAL_NO_TOKENS: frozenset[str] = frozenset(
    {
        # RU tokens
        "а",
        "ага",
        "ах",
        "аха",
        "бай",
        "большое",
        "браво",
        "без",
        "блин",
        "благодарю",
        "благодарствую",
        "вас",
        "вау",
        "всего",
        "все",
        "всё",
        "вечера",
        "вечер",
        "вот",
        "впрочем",
        "да",
        "давай",
        "давайте",
        "день",
        "дела",
        "дня",
        "доброго",
        "доброй",
        "доброе",
        "добрый",
        "до",
        "его",
        "ей",
        "ему",
        "еще",
        "ещё",
        "естественно",
        "жизнь",
        "жаль",
        "завтра",
        "замечательно",
        "здарова",
        "здорово",
        "здравствуй",
        "здравствуйте",
        "идеально",
        "извини",
        "извините",
        "именно",
        "интересно",
        "йо",
        "йоу",
        "как",
        "кек",
        "класс",
        "классно",
        "клево",
        "клёво",
        "конечно",
        "круто",
        "крутяк",
        "ку",
        "ладно",
        "лол",
        "мне",
        "может",
        "молодец",
        "на",
        "наверное",
        "наверно",
        "настроение",
        "не",
        "неа",
        "нет",
        "ничего",
        "нового",
        "ну",
        "нужна",
        "нужна",
        "нужно",
        "норм",
        "нормально",
        "ого",
        "огромное",
        "ок",
        "окей",
        "отлично",
        "очень",
        "пардон",
        "погоди",
        "пожалуйста",
        "пока",
        "понял",
        "поняла",
        "понятно",
        "прекрасно",
        "принято",
        "принял",
        "прости",
        "простите",
        "привет",
        "приветик",
        "про",
        "проблема",
        "проблем",
        "продолжай",
        "продолжайте",
        "прощай",
        "раз",
        "разумеется",
        "рад",
        "рада",
        "ржу",
        "сам",
        "сама",
        "секунду",
        "секундочку",
        "серьезно",
        "серьёзно",
        "скорого",
        "слушаю",
        "смешно",
        "согласен",
        "согласна",
        "сори",
        "сорри",
        "спасибо",
        "спасибочки",
        "спокойной",
        "спс",
        "стой",
        "стоп",
        "супер",
        "счастливо",
        "так",
        "там",
        "тебя",
        "точно",
        "ты",
        "удачи",
        "увидимся",
        "умница",
        "утра",
        "утро",
        "угу",
        "хай",
        "хаха",
        "хахаха",
        "хм",
        "хмм",
        "хорошего",
        "хорошо",
        "хз",
        "что",
        "шикарно",
        "это",
        "ясно",
        "встречи",
        "великолепно",
        "безусловно",
        "верно",
        "возможно",
        "говори",
        "доброго",
        "знаю",
        "минутку",
        "наверное",
        "не",
        "ничего",
        "обратно",
        "пожалуй",
        "помоги",
        "помогите",
        "прошло",
        "работаешь",
        "связи",
        "стоит",
        "тут",
        "здесь",
        "живой",
        "живая",
        # EN tokens
        "a",
        "absolutely",
        "again",
        "ah",
        "aha",
        "alright",
        "amazing",
        "anyone",
        "anytime",
        "appreciate",
        "are",
        "awesome",
        "bad",
        "be",
        "begin",
        "brb",
        "brilliant",
        "buddy",
        "bye",
        "can",
        "certainly",
        "cheers",
        "come",
        "continue",
        "correct",
        "course",
        "cya",
        "day",
        "definitely",
        "didnt",
        "didn't",
        "doing",
        "dont",
        "don't",
        "dope",
        "doubt",
        "dunno",
        "evening",
        "everyone",
        "exactly",
        "excuse",
        "fair",
        "fantastic",
        "farewell",
        "fine",
        "for",
        "forgive",
        "get",
        "go",
        "going",
        "good",
        "goodbye",
        "got",
        "gotcha",
        "great",
        "gtg",
        "gotta",
        "guess",
        "have",
        "hehe",
        "hello",
        "help",
        "here",
        "hey",
        "hi",
        "hold",
        "how",
        "howdy",
        "huh",
        "i",
        "idk",
        "im",
        "i'm",
        "indeed",
        "it",
        "its",
        "it's",
        "jk",
        "job",
        "just",
        "k",
        "keep",
        "kk",
        "kidding",
        "know",
        "later",
        "let",
        "lets",
        "let's",
        "life",
        "listening",
        "lit",
        "lmao",
        "lol",
        "lovely",
        "luck",
        "makes",
        "many",
        "mate",
        "maybe",
        "me",
        "mention",
        "mistake",
        "moment",
        "morning",
        "much",
        "my",
        "nah",
        "nay",
        "need",
        "nice",
        "night",
        "no",
        "not",
        "now",
        "nope",
        "off",
        "oh",
        "ohh",
        "ok",
        "okay",
        "okey",
        "omg",
        "on",
        "one",
        "perhaps",
        "perfect",
        "pardon",
        "please",
        "pls",
        "plz",
        "pleasure",
        "precisely",
        "probably",
        "problem",
        "problems",
        "really",
        "repeat",
        "right",
        "rofl",
        "sec",
        "second",
        "see",
        "seriously",
        "signing",
        "sick",
        "sleep",
        "so",
        "sorry",
        "sound",
        "sounds",
        "start",
        "still",
        "stop",
        "sup",
        "sure",
        "sweet",
        "take",
        "talk",
        "thank",
        "thanks",
        "that",
        "there",
        "thx",
        "to",
        "true",
        "ttyl",
        "ty",
        "tysm",
        "tyvm",
        "u",
        "uh",
        "uhh",
        "um",
        "umm",
        "understand",
        "understood",
        "up",
        "ugh",
        "very",
        "wait",
        "was",
        "way",
        "we",
        "well",
        "welcome",
        "were",
        "what",
        "whats",
        "what's",
        "when",
        "whoa",
        "who",
        "wonderful",
        "work",
        "works",
        "wow",
        "wassup",
        "worry",
        "worries",
        "ya",
        "yea",
        "yeah",
        "yep",
        "yes",
        "you",
        "youre",
        "you're",
        "your",
        "yup",
        "yo",
    }
)

# Max words in an all-token trivial message.
TRIVIAL_NO_MAX_TOKEN_WORDS = 5

_GREETING_HINTS: frozenset[str] = frozenset(
    {
        "привет", "приветик", "здравствуй", "здравствуйте", "добрый", "доброе", "доброй",
        "доброго", "салют", "хай", "хелло", "хеллоу", "hello", "hi", "hey", "heya", "hiya",
        "howdy", "yo", "sup", "wassup", "morning", "evening", "gm", "gn", "good",
    }
)


def normalize_trivial_text(text: str) -> str:
    """Lowercase, collapse whitespace, strip trailing punctuation."""
    import re

    t = text.lower().strip()
    t = re.sub(r"[!?.,;:…]+", " ", t)
    t = re.sub(r"\s+", " ", t).strip()
    return t


def is_trivial_chat_message(text: str) -> bool:
    """True when the message is small talk / ack — skip web classifier and mind LLM preflight."""
    norm = normalize_trivial_text(text)
    if not norm:
        return True
    if norm in TRIVIAL_NO_PHRASES:
        return True
    words = norm.split()
    if len(words) <= TRIVIAL_NO_MAX_TOKEN_WORDS and all(w in TRIVIAL_NO_TOKENS for w in words):
        return True
    return False


def is_trivial_greeting_message(text: str) -> bool:
    norm = normalize_trivial_text(text)
    if not norm:
        return False
    words = set(norm.split())
    if words & _GREETING_HINTS:
        return True
    for hint in ("good morning", "good afternoon", "good evening", "good night", "how are you", "как дела"):
        if hint in norm:
            return True
    return False
